# Generated by Django 5.1.2 on 2024-11-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='https://picsum.photos/200/300', upload_to='', verbose_name='images/'),
        ),
    ]
