# Generated by Django 5.1.2 on 2024-11-01 12:34

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_blog_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
        migrations.AddField(
            model_name='blog',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_to),
        ),
    ]
