# Generated by Django 5.1.2 on 2024-12-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0002_familymember_address_familymember_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='married',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
